const subsectionTitles24 = {
  moduleNumber: 2,
  sectionNumber: 4,
  subsections: [
    {
      docId: "introduction-2.4.1",
      subsectionNumber: 1,
      displayOrder: 1,
      isCourseSubsection: false,
      title: "Why is this section important?",
    },
    {
      subsectionNumber: 1,
      displayOrder: 2,
      title: "The importance of involving family and friends",
    },
    {
      subsectionNumber: 2,
      displayOrder: 3,
      title: "Types of help and support that you might need",
    },
    {
      docId: "activity-2.4.1",
      subsectionNumber: 1,
      displayOrder: 4,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "activity-2.4.2",
      subsectionNumber: 2,
      displayOrder: 5,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "activity-2.4.3",
      subsectionNumber: 3,
      displayOrder: 6,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "activity-2.4.4",
      subsectionNumber: 4,
      displayOrder: 7,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "activity-2.4.5",
      subsectionNumber: 5,
      displayOrder: 8,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "activity-2.4.6",
      subsectionNumber: 6,
      displayOrder: 9,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "subsection-2.4.2-continued-1",
      subsectionNumber: 2,
      displayOrder: 10,
      title: "Types of help and support that you might need (continued)",
    },
    {
      docId: "subsection-2.4.2-continued-2",
      subsectionNumber: 2,
      displayOrder: 11,
      title: "Types of help and support that you might need (continued)",
    },
    {
      docId: "activity-2.4.7",
      subsectionNumber: 7,
      displayOrder: 12,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "subsection-2.4.2-continued-3",
      subsectionNumber: 2,
      displayOrder: 13,
      title: "Types of help and support that you might need (continued)",
    },
    {
      subsectionNumber: 3,
      displayOrder: 14,
      title: "Effectively asking for help from others",
    },
    {
      docId: "activity-2.4.8",
      subsectionNumber: 8,
      displayOrder: 15,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "activity-2.4.9",
      subsectionNumber: 9,
      displayOrder: 16,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "activity-2.4.10",
      subsectionNumber: 10,
      displayOrder: 17,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      docId: "activity-2.4.11",
      subsectionNumber: 11,
      displayOrder: 18,
      isCourseSubsection: false,
      title: "Activity",
    },
    {
      subsectionNumber: 4,
      displayOrder: 19,
      title: "Respite services and additional support",
    },
  ],
};

export default subsectionTitles24;
